#pragma once

#include <Windows.h>

#if !defined(_WIN64)
#error miniEDR telemetry wire format requires a 64-bit GUI build
#endif

#define MINI_EDR_PATH_CAPACITY 256

// Events
#define EVENT_PROCESS_CLOSE ((ULONG)0)
#define EVENT_PROCESS_CREATE ((ULONG)1)

#define EVENT_FILE_MAPPED ((ULONG)3)

#define EVENT_FILE_CREATE ((ULONG)4)
#define EVENT_FILE_WRITE ((ULONG)5)
#define EVENT_FILE_RENAME ((ULONG)6)
#define EVENT_FILE_DELETE ((ULONG)7)
#define EVENT_FILE_SET_INFORMATION ((ULONG)8)

#define EVENT_NETWORK_CONNECT ((ULONG)9)


typedef struct _EVENT_PROCESS_CREATE_CLOSE_PIPE
{
	HANDLE ProcessId;
	HANDLE ProcessParentId;

	LARGE_INTEGER Timestamp;

	WCHAR ImagePath[MINI_EDR_PATH_CAPACITY];

} EVENT_PROCESS_CREATE_CLOSE_PIPE, * PEVENT_PROCESS_CREATE_CLOSE_PIPE;

typedef struct _EVENT_FILE_MAPPED_PIPE
{
	HANDLE ProcessId;

	LARGE_INTEGER Timestamp;

	PVOID ImageBase;
	SIZE_T ImageSize;

	ULONG SystemModeImage;
	ULONG ImageSignatureLevel;
	ULONG ImageSignatureType;

	WCHAR ImagePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_MAPPED_PIPE, * PEVENT_FILE_MAPPED_PIPE;

typedef struct _EVENT_FILE_CREATE_PIPE
{
	HANDLE ProcessId;
	HANDLE ThreadId;

	LARGE_INTEGER Timestamp;

	NTSTATUS Status;

	ACCESS_MASK DesiredAccess;
	ULONG CreateDisposition;
	ULONG CreateOptions;
	ULONG FileAttributes;
	ULONG ShareAccess;

	ULONG RequestorMode;

	WCHAR FilePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_CREATE_PIPE, * PEVENT_FILE_CREATE_PIPE;

typedef struct _EVENT_FILE_WRITE_PIPE
{
	HANDLE ProcessId;
	HANDLE ThreadId;

	LARGE_INTEGER Timestamp;

	NTSTATUS Status;

	ULONG RequestedLength;
	ULONG_PTR BytesWritten;

	LARGE_INTEGER ByteOffset;

	ULONG RequestorMode;

	WCHAR FilePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_WRITE_PIPE, * PEVENT_FILE_WRITE_PIPE;

typedef struct _EVENT_FILE_RENAME_PIPE
{
	HANDLE ProcessId;
	HANDLE ThreadId;

	LARGE_INTEGER Timestamp;

	NTSTATUS Status;

	ULONG InformationClass;
	ULONG RequestorMode;

	BOOLEAN ReplaceIfExists;

	WCHAR FilePath[MINI_EDR_PATH_CAPACITY];
	WCHAR NewFilePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_RENAME_PIPE, * PEVENT_FILE_RENAME_PIPE;

typedef struct _EVENT_FILE_DELETE_PIPE
{
	HANDLE ProcessId;
	HANDLE ThreadId;

	LARGE_INTEGER Timestamp;

	NTSTATUS Status;

	ULONG InformationClass;
	ULONG RequestorMode;

	BOOLEAN DeleteFile;

	WCHAR FilePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_DELETE_PIPE, * PEVENT_FILE_DELETE_PIPE;

typedef struct _EVENT_FILE_SET_INFORMATION_PIPE
{
	HANDLE ProcessId;
	HANDLE ThreadId;

	LARGE_INTEGER Timestamp;

	NTSTATUS Status;

	ULONG InformationClass;
	ULONG RequestorMode;

	WCHAR FilePath[MINI_EDR_PATH_CAPACITY];

} EVENT_FILE_SET_INFORMATION_PIPE, * PEVENT_FILE_SET_INFORMATION_PIPE;

typedef struct _EVENT_NETWORK_CONNECT_PIPE
{
	HANDLE ProcessId;

	LARGE_INTEGER Timestamp;

	UINT8 Protocol;

	UINT32 LocalAddress;
	UINT32 RemoteAddress;

	UINT16 LocalPort;
	UINT16 RemotePort;

} EVENT_NETWORK_CONNECT_PIPE, * PEVENT_NETWORK_CONNECT_PIPE;



/// FINAL TYPES FOR NAMED PIPE

typedef struct _FINAL_STRUCT_PROCESS_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_PROCESS_CREATE_CLOSE_PIPE Data;

} FINAL_STRUCT_PROCESS_EVENT, * PFINAL_STRUCT_PROCESS_EVENT;

typedef struct _FINAL_STRUCT_FILE_MAPPED_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_MAPPED_PIPE Data;

} FINAL_STRUCT_FILE_MAPPED_EVENT, * PFINAL_STRUCT_FILE_MAPPED_EVENT;

typedef struct _FINAL_STRUCT_FILE_CREATE_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_CREATE_PIPE Data;

} FINAL_STRUCT_FILE_CREATE_EVENT, * PFINAL_STRUCT_FILE_CREATE_EVENT;

typedef struct _FINAL_STRUCT_FILE_WRITE_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_WRITE_PIPE Data;

} FINAL_STRUCT_FILE_WRITE_EVENT, * PFINAL_STRUCT_FILE_WRITE_EVENT;

typedef struct _FINAL_STRUCT_FILE_RENAME_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_RENAME_PIPE Data;

} FINAL_STRUCT_FILE_RENAME_EVENT, * PFINAL_STRUCT_FILE_RENAME_EVENT;

typedef struct _FINAL_STRUCT_FILE_DELETE_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_DELETE_PIPE Data;

} FINAL_STRUCT_FILE_DELETE_EVENT, * PFINAL_STRUCT_FILE_DELETE_EVENT;

typedef struct _FINAL_STRUCT_FILE_SET_INFORMATION_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_FILE_SET_INFORMATION_PIPE Data;

} FINAL_STRUCT_FILE_SET_INFORMATION_EVENT,
* PFINAL_STRUCT_FILE_SET_INFORMATION_EVENT;

typedef struct _FINAL_STRUCT_NETWORK_CONNECT_EVENT {

	ULONG EventType;

	ULONG Size;

	EVENT_NETWORK_CONNECT_PIPE Data;

} FINAL_STRUCT_NETWORK_CONNECT_EVENT, * PFINAL_STRUCT_NETWORK_CONNECT_EVENT;


// Header
typedef struct _PIPE_EVENT_HEADER
{
	ULONG EventType;
	ULONG Size;

} PIPE_EVENT_HEADER;
